name: Copy Files On Push

on:
  push:
    branches:
      - main  # oder den Namen Ihrer Hauptentwicklungsbranch

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Copy Files
        if: ${{ github.event_name == 'push' && contains(github.event.commits[0].added, 'files_new/') }}
        run: |
          git clone https://github.com/matze240/second_repo.git second_repo_temp
          cp -r second_repo_temp/data_new/* files_new/
          rm -rf second_repo_temp
          git add files_new/
          git commit -m "Update files from second_repo"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
