name: collect_and_push_and_transfer
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Clone 'other_repo'
        run: git clone https://github.com/matze240/second_repo.git
        # Replace 'username' with the owner of the repository

      - name: Copy 'data' folder
        run: cp -r files_new second_repo/

      - name: Commit changes in 'second_repo'
        run: |
          cd second_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze240"
          git add .
          git commit -m "Added 'files_new' folder from main branch"
          git push origin main
      
      - name: Checkout new_Branch
        run: git checkout -b new_Branch main
  
      - name: Copy 'files' folder from 'other_repo'
        run: cp -r second_repo/data_new .
  
      - name: Commit changes
        run: |
          git add .
          git config --global user.email "you@example.com"
          git config --global user.name "Matze2402"
          git config --global url.https://${{ secrets.NEXT_TOKEN }}@github.com/.insteadOf https://github.com/
          git commit -m "Moved 'data' folder to other_Branch and included 'files' folder from other_repo"
  
      - name: Push changes
        run: git push origin new_Branch

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze2402/main_repo.git main_repo
        # Replace 'yourusername' with your GitHub username and 'target-repo' with the name of your target repository

      - name: Copy folder to target repository
        run: |
          cp -r files_new/* main_repo/temporary/things
          cp -r data_new/* main_repo/temporary/things
          cd main_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.next_token}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Copy files from source repository"
          git push origin temporary
