name: Copy Files On Push

on:
  push:
    branches:
      - main  # oder den Namen Ihrer Hauptentwicklungsbranch
    paths:
      - 'files_new/*.md'

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Copy Files
        run: |
          git clone https://github.com/matze240/second_repo.git second_repo_temp
          cp -r second_repo_temp/data_new/* files_new/
          rm -rf second_repo_temp
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"  	#Dein Username in github
          git config --global url.https://${{ secrets.next_token}}@github.com/.insteadOf https://github.com/
          git add files_new/
          git commit -m "Update files from second_repo"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch trigger for parent
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.next_token }}
          repository: Matze2402/next_repo
          event-type: parent

