name: transfer_files
on:
  push:
    branches:
      - main

jobs:
  transfer_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Clone second_repo
        run: git clone https://github.com/matze240/second_repo.git

      - name: Copy files from data_new to combined (overwrite)
        run: |
          rsync -av --ignore-existing second_repo/data_new/. combined/
        working-directory: ./temp_repo

      - name: Copy files from files_new to combined (skip if exists)
        run: |
          for file in files_new/*; do
            if [[ ! -f combined/$(basename $file) ]]; then
              cp $file combined/
            fi
          done
        working-directory: ./temp_repo

      - name: Commit and push changes to temp_repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global url.https://${{ secrets.next_token}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Transfer files from next_repo and second_repo"
          git push origin main
