name: Copy Files On Push

on:
  push:
    branches:
      - main  # oder den Namen Ihrer Hauptentwicklungsbranch

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Copy Files
        run: |
          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- files_new/) ]]; then
            git clone https://github.com/matze240/second_repo.git second_repo_temp
            cp -r second_repo_temp/data_new/* files_new/
            rm -rf second_repo_temp
            git add files_new/
            git commit -m "Update files from second_repo"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.next_token }}
