name: Copy All Files to Another Directory

on:
 repository_dispatch:
    types: [parent]

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Copy files to new directory
        run: |
          mkdir -p temp_folder
          cp -r files_new/* temp_folder/
